-- Kaua Almeida Silveira - RM 552618
-- Matheus Alexandre Benites Scotti - RM 553073
-- Mariana Spinola - RM 553476

-- Drop das tabelas, removendo todas as restricoes de chave estrangeira referenciadas em cascata.
DROP TABLE TB_CONTA CASCADE CONSTRAINTS;
DROP TABLE TB_PESSOA CASCADE CONSTRAINTS;
DROP TABLE TB_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE TB_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE TB_SERVICO CASCADE CONSTRAINTS;
DROP TABLE TB_SERVICO_CONTA CASCADE CONSTRAINTS;
DROP TABLE TB_PEDIDO CASCADE CONSTRAINTS;
DROP TABLE TB_PAGAMENTO  CASCADE CONSTRAINTS;

-- Criacao da tabela TB_EMPRESA
CREATE TABLE TB_EMPRESA (
    ID_EMPRESA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(50) NOT NULL,
    DEPARTAMENTO VARCHAR2(15),
    DIVISAO VARCHAR2(50),
    NUM_FUNCIONARIO NUMBER NOT NULL,
    INICIO_JORNADA VARCHAR2(8) DEFAULT '09:00:00',
    FIM_JORNADA VARCHAR2(8) DEFAULT '18:00:00'
);


-- Adiciona uma chave primaria na tabela TB_EMPRESA
ALTER TABLE TB_EMPRESA
ADD CONSTRAINT PK_TB_EMPRESA_ID_EMPRESA PRIMARY KEY (ID_EMPRESA);


-- Criacao da tabela TB_ENDERECO
CREATE TABLE TB_ENDERECO (
    ID_ENDERECO NUMBER GENERATED ALWAYS AS IDENTITY,
    RUA VARCHAR2(50),
    CIDADE VARCHAR2(30),
    ESTADO VARCHAR2(50),
    CEP VARCHAR2(10),
    PAIS VARCHAR2(50) NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_ENDERECO
ALTER TABLE TB_ENDERECO
ADD CONSTRAINT PK_TB_ENDERECO PRIMARY KEY (ID_ENDERECO);


-- Criacao da tabela TB_PESSOA
CREATE TABLE TB_PESSOA (
    ID_PESSOA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(50) NOT NULL,
    SOBRENOME VARCHAR2(100) NOT NULL,
    APELIDO VARCHAR2(30),
    TELEFONE VARCHAR2(9),
    CELULAR VARCHAR2(19),
    CARGO VARCHAR2(30) NOT NULL,
    RG VARCHAR2(12),
    ID_ENDERECO NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_PESSOA
ALTER TABLE TB_PESSOA
ADD CONSTRAINT PK_TB_PESSOA PRIMARY KEY (ID_PESSOA);

-- Adiciona uma chave estrangeira na tabela TB_PESSOA referenciando TB_EMPRESA
ALTER TABLE TB_PESSOA
ADD CONSTRAINT FK_TB_PESSOA_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES TB_EMPRESA(ID_EMPRESA);

-- Adiciona uma chave estrangeira na tabela TB_PESSOA referenciando TB_ENDERECO
ALTER TABLE TB_PESSOA
ADD CONSTRAINT FK_TB_PESSOA_ENDERECO
FOREIGN KEY (ID_ENDERECO)
REFERENCES TB_ENDERECO(ID_ENDERECO);


-- Criacao da tabela TB_CONTA
CREATE TABLE TB_CONTA (
    ID_CONTA NUMBER GENERATED ALWAYS AS IDENTITY,
    USUARIO VARCHAR2(50),
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DATA_REGISTRO DATE DEFAULT SYSDATE,
    ULTIMO_ACESSO TIMESTAMP DEFAULT SYSDATE,
    ID_PESSOA NUMBER NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_CONTA
ALTER TABLE TB_CONTA
ADD CONSTRAINT PK_TB_CONTA PRIMARY KEY (ID_CONTA);

ALTER TABLE TB_CONTA
ADD CONSTRAINT CHK_STATUS CHECK (STATUS IN ('Ativo', 'Inativo'));

-- Adiciona uma chave estrangeira na tabela TB_CONTA referenciando TB_PESSOA
ALTER TABLE TB_CONTA
ADD CONSTRAINT FK_TB_CONTA_PESS0A
FOREIGN KEY (ID_PESSOA)
REFERENCES TB_PESSOA(ID_PESSOA);


-- Criacao da tabela TB_SERVICO
CREATE TABLE TB_SERVICO (
    ID_SERVICO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(50) NOT NULL,
    DESCRICAO VARCHAR2(255),
    CATEGORIA VARCHAR2(50) NOT NULL,
    VALOR NUMBER(10, 2) NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_SERVICO
ALTER TABLE TB_SERVICO
ADD CONSTRAINT PK_TB_SERVICO PRIMARY KEY (ID_SERVICO);


-- Criacao da tabela TB_SERVICO_CONTA
CREATE TABLE TB_SERVICO_CONTA (
    ID_SERVICO NUMBER NOT NULL,
    ID_CONTA NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DATA_INICIO DATE DEFAULT SYSDATE NOT NULL,
    DATA_TERMINO DATE DEFAULT NULL
);

ALTER TABLE TB_SERVICO_CONTA
ADD CONSTRAINT CHK_STATUS CHECK (STATUS IN ('Ativo', 'Inativo'));

-- Adiciona uma chave estrangeira na tabela TB_SERVICO_CONTA referenciando TB_SERVICO
ALTER TABLE TB_SERVICO_CONTA
ADD CONSTRAINT FK_TB_SERVICO_CONTA_SERVICO
FOREIGN KEY (ID_SERVICO)
REFERENCES TB_SERVICO(ID_SERVICO);

-- Adiciona uma chave estrangeira na tabela TB_SERVICO_CONTA referenciando TB_CONTA
ALTER TABLE TB_SERVICO_CONTA
ADD CONSTRAINT FK_TB_SERVICO_CONTA_CONTA
FOREIGN KEY (ID_CONTA)
REFERENCES TB_CONTA(ID_CONTA);


-- Criacao da tabela TB_PAGAMENTO
CREATE TABLE TB_PAGAMENTO (
    ID_PAGAMENTO NUMBER GENERATED ALWAYS AS IDENTITY,
    DATA_PAGAMENTO DATE DEFAULT SYSDATE NOT NULL,
    VALOR_TOTAL NUMBER(10 ,2) NOT NULL,
    FORMA_PAGAMENTO VARCHAR2(50) NOT NULL,
    PARCELAS NUMBER NOT NULL,
    VALOR_PARCELAS NUMBER(10, 2) NOT NULL,
    DESCRICAO VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_PAGAMENTO
ALTER TABLE TB_PAGAMENTO
ADD CONSTRAINT PK_TB_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO);

-- Adiciona constraint de check para o status do pagamento
ALTER TABLE TB_PAGAMENTO
ADD CONSTRAINT CHK_STATUS CHECK (STATUS IN ('Pago', 'Pendente', 'Cancelado', 'Falha', 'Processando', 'Atrasado', 'Reembolsado'));


-- Criacao da tabela TB_PEDIDO
CREATE TABLE TB_PEDIDO (
    ID_PEDIDO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CONTA NUMBER,
    ID_PAGAMENTO NUMBER,
    ID_SERVICO NUMBER,
    DATA_PEDIDO DATE DEFAULT SYSDATE NOT NULL
);

-- Adiciona uma chave primaria na tabela TB_PEDIDO
ALTER TABLE TB_PEDIDO
ADD CONSTRAINT PK_TB_PEDIDO PRIMARY KEY (ID_PEDIDO);

-- Adiciona uma chave estrangeira na tabela TB_PEDIDO referenciando TB_CONTA
ALTER TABLE TB_PEDIDO
ADD CONSTRAINT FK_TB_PEDIDO_CONTA
FOREIGN KEY (ID_CONTA)
REFERENCES TB_CONTA(ID_CONTA);

-- Adiciona uma chave estrangeira na tabela TB_PEDIDO referenciando TB_PAGAMENTO
ALTER TABLE TB_PEDIDO
ADD CONSTRAINT FK_TB_PEDIDO_PAGAMENTO
FOREIGN KEY (ID_PAGAMENTO)
REFERENCES TB_PAGAMENTO(ID_PAGAMENTO);

-- Adiciona uma chave estrangeira na tabela TB_PEDIDO referenciando TB_SERVICO
ALTER TABLE TB_PEDIDO
ADD CONSTRAINT FK_TB_PEDIDO_SERVICO
FOREIGN KEY (ID_SERVICO)
REFERENCES TB_SERVICO(ID_SERVICO);

---
    
SELECT * FROM TB_PESSOA;
SELECT * FROM TB_CONTA;
SELECT * FROM TB_SERVICO;
SELECT * FROM TB_SERVICO_CONTA;
SELECT * FROM TB_PEDIDO;
SELECT * FROM TB_PAGAMENTO;
