DROP TABLE TB_CONTA;
DROP TABLE TB_PESSOA;
DROP TABLE TB_ENDERECO;
DROP TABLE TB_EMPRESA;

CREATE TABLE TB_EMPRESA (
    ID_EMPRESA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(50),
    DIVISAO VARCHAR2(50),
    NUM_FUNCIONARIO NUMBER,
    INICIO_JORNADA TIMESTAMP DEFAULT SYSDATE,
    FIM_JORNADA TIMESTAMP DEFAULT SYSDATE
);

ALTER TABLE TB_EMPRESA
ADD CONSTRAINT PK_TB_EMPRESA_ID_EMPRESA PRIMARY KEY (ID_EMPRESA);


CREATE TABLE TB_ENDERECO (
    ID_ENDERECO NUMBER GENERATED ALWAYS AS IDENTITY,
    RUA VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(50) NOT NULL,
    ESTADO VARCHAR2(50),
    CEP VARCHAR2(10) NOT NULL,
    PAIS VARCHAR2(50)
);

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT PK_TB_ENDERECO PRIMARY KEY (ID_ENDERECO)

CREATE TABLE TB_PESSOA (
    ID_PESSOA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    APELIDO VARCHAR2(50),
    TELEFONE VARCHAR2(20),
    CELULAR VARCHAR2(20) NOT NULL,
    CARGO VARCHAR2(50) NOT NULL,
    RG VARCHAR2(20) NOT NULL,
    ID_ENDERECO NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL
);

ALTER TABLE TB_PESSOA
ADD CONSTRAINT PK_TB_PESSOA PRIMARY KEY (ID_PESSOA)

ALTER TABLE TB_PESSOA
ADD CONSTRAINT FK_TB_PESSOA_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES TB_EMPRESA(ID_EMPRESA)

ALTER TABLE TB_PESSOA
ADD CONSTRAINT FK_TB_PESSOA_ENDERECO
FOREIGN KEY (ID_ENDERECO)
REFERENCES TB_ENDERECO(ID_ENDERECO)

CREATE TABLE TB_CONTA (
    ID_CONTA NUMBER GENERATED ALWAYS AS IDENTITY,
    USUARIO VARCHAR2(50),
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(50) NOT NULL,
    DATA_REGISTRO DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) NOT NULL,
    ULTIMO_ACESSO DATE DEFAULT SYSDATE,
    ID_PESSOA NUMBER
);

ALTER TABLE TB_CONTA
ADD CONSTRAINT PK_TB_CONTA PRIMARY KEY (ID_CONTA)

ALTER TABLE TB_CONTA
ADD CONSTRAINT FK_TB_CONTA_PESS0A
FOREIGN KEY (ID_PESSOA)
REFERENCES TB_PESSOA(ID_PESSOA)
